name: Bug report
description: Bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please explain the issue with documentation
  - type: textarea
    id: issue_described
    attributes:
      label: Tell us about the problem
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the problem in as much details as possible.
    validations:
      required: true
  - type: textarea
    id: debug_log
    attributes:
      label: Stacktrace
      description: If you have a stacktrace paste it here
    validations:
      required: false
