name: Documentation
description: Documentation feedback
title: "[Feedback]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please explain the issue with documentation
  - type: textarea
    id: what-happened
    attributes:
      label: Tell us about the problem
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the problem in as much details as possible.
    validations:
      required: true
  - type: dropdown
    id: documentation_type
    attributes:
      label: Type of issue
      description: What kind of issue is it?
      options:
        - Missing information
        - wrong information
    validations:
      required: true
