name: Feedback
description: File a bug report
title: "[Issue]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the problem in as much details as possible.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What kind of issue is it?
      options:
        - Bug (code)
        - Proposed improvement
        - feature request
        - wrong information (documentation)
    validations:
      required: true
